# This is a basic workflow that is manually triggered

name: Create issue

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      title:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Title'
        # Default value if no value is explicitly provided
        default: 'Automatic issue'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  open_issue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Open issue
      run: gh issue create --title "${{ github.event.inputs.title }}" --body "This is a test issue automatically created by Create issue workflow." --repo $GITHUB_REPOSITORY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
