name: Run fastlane
on: workflow_dispatch
jobs:
  lane:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: maierj/fastlane-action@v2.1.0
      with:
        lane: custom_lane
        options:
          do_something: true
